/* tslint:disable */
require("./CustomerContactCards.module.css");
const styles = {
  saSelect: 'saSelect_25ab3eb7',
  accordionHeader: 'accordionHeader_25ab3eb7',
  tab: 'tab_25ab3eb7',
  callButton: 'callButton_25ab3eb7',
  backButton: 'backButton_25ab3eb7',
  pageBtn: 'pageBtn_25ab3eb7',
  card: 'card_25ab3eb7',
  clearButton: 'clearButton_25ab3eb7',
  filterSelect: 'filterSelect_25ab3eb7',
  webPartContainer: 'webPartContainer_25ab3eb7',
  pageHeading: 'pageHeading_25ab3eb7',
  gridView: 'gridView_25ab3eb7',
  filterBar: 'filterBar_25ab3eb7',
  filterGroup: 'filterGroup_25ab3eb7',
  filterLabel: 'filterLabel_25ab3eb7',
  filterChip: 'filterChip_25ab3eb7',
  searchWrapper: 'searchWrapper_25ab3eb7',
  searchIcon: 'searchIcon_25ab3eb7',
  searchInput: 'searchInput_25ab3eb7',
  countText: 'countText_25ab3eb7',
  cardGrid: 'cardGrid_25ab3eb7',
  emptyState: 'emptyState_25ab3eb7',
  cardAvatar: 'cardAvatar_25ab3eb7',
  cardName: 'cardName_25ab3eb7',
  cardTypeBadge: 'cardTypeBadge_25ab3eb7',
  cardMeta: 'cardMeta_25ab3eb7',
  cardMetaRow: 'cardMetaRow_25ab3eb7',
  cardMetaIcon: 'cardMetaIcon_25ab3eb7',
  cardEmail: 'cardEmail_25ab3eb7',
  pagination: 'pagination_25ab3eb7',
  pageIndicator: 'pageIndicator_25ab3eb7',
  detailView: 'detailView_25ab3eb7',
  detailHeader: 'detailHeader_25ab3eb7',
  detailHeaderLeft: 'detailHeaderLeft_25ab3eb7',
  detailName: 'detailName_25ab3eb7',
  detailTypePill: 'detailTypePill_25ab3eb7',
  detailRole: 'detailRole_25ab3eb7',
  detailBio: 'detailBio_25ab3eb7',
  detailHeaderActions: 'detailHeaderActions_25ab3eb7',
  headerDivider: 'headerDivider_25ab3eb7',
  tabBar: 'tabBar_25ab3eb7',
  tabActive: 'tabActive_25ab3eb7',
  tabPanel: 'tabPanel_25ab3eb7',
  sectionsGrid: 'sectionsGrid_25ab3eb7',
  sectionColumn: 'sectionColumn_25ab3eb7',
  fullWidthSection: 'fullWidthSection_25ab3eb7',
  accordionSection: 'accordionSection_25ab3eb7',
  accordionTitle: 'accordionTitle_25ab3eb7',
  accordionChevron: 'accordionChevron_25ab3eb7',
  accordionChevronOpen: 'accordionChevronOpen_25ab3eb7',
  accordionBody: 'accordionBody_25ab3eb7',
  accordionBodyOpen: 'accordionBodyOpen_25ab3eb7',
  accordionBodyInner: 'accordionBodyInner_25ab3eb7',
  instructionGroup: 'instructionGroup_25ab3eb7',
  instructionGroupTitle: 'instructionGroupTitle_25ab3eb7',
  instructionList: 'instructionList_25ab3eb7',
  instructionSubList: 'instructionSubList_25ab3eb7',
  serviceAmendments: 'serviceAmendments_25ab3eb7',
  saLabel: 'saLabel_25ab3eb7',
  saInstructions: 'saInstructions_25ab3eb7',
  contactInfoContent: 'contactInfoContent_25ab3eb7',
  businessHoursLabel: 'businessHoursLabel_25ab3eb7',
  businessHoursValue: 'businessHoursValue_25ab3eb7',
  contactInfoGrid: 'contactInfoGrid_25ab3eb7',
  contactInfoCard: 'contactInfoCard_25ab3eb7',
  contactInfoCardTitle: 'contactInfoCardTitle_25ab3eb7',
  contactInfoCardTitleMuted: 'contactInfoCardTitleMuted_25ab3eb7',
  contactInfoDivider: 'contactInfoDivider_25ab3eb7',
  contactInfoSection: 'contactInfoSection_25ab3eb7',
  contactInfoSectionTitle: 'contactInfoSectionTitle_25ab3eb7'
};

export default styles;
/* tslint:enable */